apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: demo
build:
  insecureRegistries:
    - registry.apps.c3smonkey.ch
  artifacts:
    - image: registry.apps.c3smonkey.ch/myproject/demo
#    - image: docker-registry.default.svc:5000/myproject/demo
      jib:
        args: ['-DskipTests' , '-Dimage=registry.apps.c3smonkey.ch/myproject/demo']
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml

