apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: docker-registry.default.svc:5000/myproject/demo
          name: demo
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256M
              cpu: 2000m
            limits:
              memory: 512M
              cpu: 4000m
          livenessProbe:
            httpGet:
              port: 8080
              path: /alive
          readinessProbe:
            periodSeconds: 5
            failureThreshold: 1
            httpGet:
              port: 8080
              path: /actuator/health

