apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myproject
 
bases:
  - ../base

commonLabels:
    env: dev

commonAnnotations:
  component: fsl-backend

images:
  - name: docker-registry.default.svc:5000/myproject/demo
    newName: 172.30.1.1:5000/myproject/demo
    newTag: 1.0.0
