apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

commonLabels:
    stage: dev

configMapGenerator:
  - name: demo
    files:
      - ./config-files/application.yaml